config/routes.rb
Rails.application.routes.draw do
  match "/maggie_wu", to: "maggiewus#maggie_wu", via: :get
  match "/erin_dexheimer", to: "maggiewus#erin_dexheimer", via: :get
  match "/musicperformances", to: "maggiewus#musicperformances", via: :get
  resources :maggiewus

  root 'maggiewus#index'

end

app/models/maggiewu.rb
class Maggiewu < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maggiewus_controller.rb
class MaggiewusController < ApplicationController
  before_action :set_maggiewu, only: [:show, :edit, :update, :destroy]

  def maggie_wu
  end

  # GET /maggiewus
  # GET /maggiewus.json
  def index
    @maggiewus = Maggiewu.all
  end

  # GET /maggiewus/1
  # GET /maggiewus/1.json
  def show
  end

  # GET /maggiewus/new
  def new
    @maggiewu = Maggiewu.new
  end

  # GET /maggiewus/1/edit
  def edit
  end

  # POST /maggiewus
  # POST /maggiewus.json
  def create
    @maggiewu = Maggiewu.new(maggiewu_params)

    respond_to do |format|
      if @maggiewu.save
        format.html { redirect_to @maggiewu, notice: 'Maggiewu was successfully created.' }
        format.json { render :show, status: :created, location: @maggiewu }
      else
        format.html { render :new }
        format.json { render json: @maggiewu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maggiewus/1
  # PATCH/PUT /maggiewus/1.json
  def update
    respond_to do |format|
      if @maggiewu.update(maggiewu_params)
        format.html { redirect_to @maggiewu, notice: 'Maggiewu was successfully updated.' }
        format.json { render :show, status: :ok, location: @maggiewu }
      else
        format.html { render :edit }
        format.json { render json: @maggiewu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maggiewus/1
  # DELETE /maggiewus/1.json
  def destroy
    @maggiewu.destroy
    respond_to do |format|
      format.html { redirect_to maggiewus_url, notice: 'Maggiewu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maggiewu
      @maggiewu = Maggiewu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maggiewu_params
      params.require(:maggiewu).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maggiewus_helper.rb
module MaggiewusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maggie</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ForteDuo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/musicperformances">Music & Performances <span class="sr-only">(current)</span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Members <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/erin_dexheimer">Erin Dexheimer</a></li>
            <li><a href="/maggie_wu">Maggie Wu</a></li>
          </ul>
        </li>
        

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>

</body>
</html>

app/views/maggiewus/_form.html.erb
<%= form_for(@maggiewu) do |f| %>
  <% if @maggiewu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maggiewu.errors.count, "error") %> prohibited this maggiewu from being saved:</h2>

      <ul>
      <% @maggiewu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maggiewus/edit.html.erb
<h1>Editing maggiewu</h1>

<%= render 'form' %>

<%= link_to 'Show', @maggiewu %> |
<%= link_to 'Back', maggiewus_path %>

app/views/maggiewus/erin_dexheimer.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>

<br><br><br><br><br>
<div class="row" style="margin: 0">
  <div class="col-md-5 col-md-offset-1">
    <%= image_tag "photo.jpg", style: "padding-top: 115px; width: 500px; height: auto" %>
  </div>
  <div class="col-md-5">
    <div class="page-title">
      Erin Dexheimer, cellist 
    </div>
    <div class="page-description">
      Type here later
    </div>
  </div>
</div>e

<style type="text/css">
  .page-title{
    font-family: "Raleway", sans-serif;
    font-size: 42px;
    font-weight: 200;
    margin-top: 148px;
  }

  .page-description{
    font-family: "Open Sans", sans-serif;
    font-size: 20px;
    font-weight: 100;
    margin-top: 30px;
    line-height: 26px;
  }
</style>

app/views/maggiewus/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>

<%= image_tag "vintageviolin.jpg", class: "giant-background-image" %>

<div class="row" style="padding-top: 80px; padding-left: 0px; padding-right: 0px; margin-left: 0px; margin-right: 0px">
  <div class="col-md-10 col-md-offset-1 black-background">
    <div class="text-center">
      <div class="cat-breath-mints">
        ForteDuo
      </div>
      <div class="description">
        Soulful music for any occasion
      </div>
    </div>
  </div>
</div>

<br><br>

<div class="row" style="padding-top: 250px; padding-left: 0px; padding-right: 0px; margin-left: 0px; margin-right: 0px">
  <div class="col-md-10 col-md-offset-1" style="position: fixed">
    <div class="text-center">
      <div align="center">
        <div class="ghost-button">
          <div class="button-text">
            Contact us
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style type="text/css">
  .button-text{
    margin-top: 11%;
  }
  .ghost-button{
    border: 10px solid white;
	  width: 300px;
	  height: 97px;
	  color: white;
	  font-family: "Open Sans", sans-serif;
	  font-size: 36px;
	  font-weight: 700;
	  cursor: pointer;
  }
  .black-background{
    background-color: rgba(0, 0, 0, 0.7);
    padding-top: 60px;
    padding-bottom: 60px;
    position: fixed;
  }
  .description{
    color: white;
    font-size: 35px;
    line-height: 50px;
    font-weight: 100;
    font-family: 'Raleway', sans-serif;
  }
  .cat-breath-mints{
    font-size: 60px;
    color: white;
    line-height: 68px;
    font-weight: bolder;
    font-family: "Open Sans", sans-serif;
  }
  .giant-background-image{
  	opacity: 0.7;
    width: 100%;
    height: auto;
    position: absolute;
    top: 0;
    left: 0;
  }
</style>

app/views/maggiewus/maggie_wu.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>

<br><br><br><br><br>
<div class="row" style="margin: 0">
  <div class="col-md-5 col-md-offset-1">
    <%= image_tag "violin.jpg", style: "padding-top: 80px; width: 500px; height: auto" %>
  </div>
  <div class="col-md-5">
    <div class="page-title">
      Maggie Wu, violinist 
    </div>
    <div class="page-description">
      Type here later
    </div>
  </div>
</div>e

<style type="text/css">
  .page-title{
    font-family: "Raleway", sans-serif;
    font-size: 42px;
    font-weight: 200;
    margin-top: 148px;
  }

  .page-description{
    font-family: "Open Sans", sans-serif;
    font-size: 20px;
    font-weight: 100;
    margin-top: 30px;
    line-height: 26px;
  }
</style>

app/views/maggiewus/musicperformances.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>

<br><br><br><br><br>
<div class="row" style="margin: 0">
  <div class="col-md-5 col-md-offset-1">
    <%= image_tag "music.jpg", style: "padding-top: 80px; width: 500px; height: auto" %>
  </div>
  <div class="col-md-5">
    <div class="page-title">
      Music & Repertoire
    </div>
    <div class="page-description">
      Type here later
    </div>
  </div>
</div>e

<style type="text/css">
  .page-title{
    font-family: "Raleway", sans-serif;
    font-size: 42px;
    font-weight: 200;
    margin-top: 148px;
  }

  .page-description{
    font-family: "Open Sans", sans-serif;
    font-size: 20px;
    font-weight: 100;
    margin-top: 30px;
    line-height: 26px;
  }
</style>

app/views/maggiewus/new.html.erb
<h1>New maggiewu</h1>

<%= render 'form' %>

<%= link_to 'Back', maggiewus_path %>

app/views/maggiewus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @maggiewu.name %>
</p>

<%= link_to 'Edit', edit_maggiewu_path(@maggiewu) %> |
<%= link_to 'Back', maggiewus_path %>